name: GitHub Actions Demo
#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
  #pull_request:
   # branches:
    #  - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: Actions/checkout@v2

      - name: Log in to Docker Hub 
        uses: docker/login-action@v1
        secrets:
          username: ${{ secret.DOCKERHUB_USERNAME }}
          password: ${{ secret.DOCKERHUB_TOCKEN }}

      - name: Build and push Docker image 
        env:
          REPOSITORY: ci-cd 
          IMAGE_TAG: latest
        run: |
          docker build -t ${{ secret.DOCKERHUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG .
          docker push ${{ secret.DOCKERHUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG 
